"""
Consolidates many individual alert items (e.g. 6 weekly NCDC Lassa fever
sitreps) into ONE outbreak-intelligence object per outbreak, with a stitched
multi-week trajectory and a single rich AI planning brief -- instead of N
near-identical weekly cards. This is what makes the feed decision-useful
rather than repetitive.

Grouping key: (disease, disease_other_label) lowercased. Trajectory is built
from each report's structured `epi_data` (extracted by news_llm), sorted by
epi_week. The planning brief is generated once per outbreak and cached by
latest epi_week, so it's only re-billed when a genuinely new week arrives.
"""
import logging
from datetime import date as _date

import news_store
from news_llm import generate_outbreak_plan, generate_signal_brief
from internal_data import internal_context_text, malaria_burden_for_states, malaria_forecast_for_states

log = logging.getLogger("news_outbreaks")

# Always show only the most recent N epidemiological weeks of an outbreak, so
# the curve is "the last 6 weeks of available reporting" regardless of how many
# historical sitreps a source lists. Surveillance data lags real time by a few
# weeks, so this is the 6 most recent AVAILABLE weeks, not literally today-6wk.
TRAJECTORY_WEEKS = 6

# Pretty display names for the fixed disease enum (label for "other" comes from
# the LLM's disease_other_label instead).
_DISEASE_PRETTY = {"malaria": "Malaria", "hiv": "HIV", "tb": "Tuberculosis"}

# Bump when the planning-brief prompt or its inputs change, to invalidate
# cached briefs generated by an older prompt.
PLAN_VERSION = "v3-today-forecast-combo"


def _outbreak_key(alert: dict) -> str:
    d = (alert.get("disease") or "unknown").lower()
    label = (alert.get("disease_other_label") or "").lower().strip()
    return f"{d}:{label}" if label else d


def _trajectory_text(points: list[dict]) -> str:
    lines = []
    for p in points:
        wk = p.get("epi_week")
        lines.append(
            f"  Week {int(wk) if wk is not None else '?'}: "
            f"{_fmt(p.get('confirmed_this_week'))} new confirmed, "
            f"{_fmt(p.get('deaths_this_week'))} deaths, "
            f"CFR {_fmt(p.get('cfr_pct'))}%, "
            f"cumulative {_fmt(p.get('cumulative_confirmed'))} cases / "
            f"{_fmt(p.get('cumulative_deaths'))} deaths, "
            f"{_fmt(p.get('states_affected'))} states / {_fmt(p.get('lgas_affected'))} LGAs"
        )
    return "\n".join(lines)


def _fmt(v):
    if v is None:
        return "n/a"
    return f"{int(v):,}" if float(v).is_integer() else f"{v}"


def _weather_text(weather: dict | None) -> str:
    if not weather:
        return ""
    fcst = weather.get("rainfall_forecast_7day_mm")
    fcst_part = f", forecast next 7d {fcst}mm rain" if fcst is not None else ""
    return (f"{weather.get('location_used')} (as of {weather.get('as_of', 'today')}): "
            f"{weather.get('temperature_c')}°C, {weather.get('humidity_pct')}% humidity, "
            f"{weather.get('rainfall_7day_mm')}mm rain (past 7d){fcst_part}. "
            f"{weather.get('note')}")


def build_outbreaks(alerts: list[dict]) -> list[dict]:
    """Returns a list of consolidated outbreak dicts (one per disease group
    that has >=1 alert-worthy item), each with a sorted trajectory, latest
    snapshot, and a cached/freshly-generated planning brief."""
    worthy = [a for a in alerts if a.get("is_alert_worthy")]
    groups: dict[str, list[dict]] = {}
    for a in worthy:
        groups.setdefault(_outbreak_key(a), []).append(a)

    plan_cache = news_store.load_plan_cache()
    outbreaks = []

    for key, items in groups.items():
        # Build trajectory points only from items that carry structured epi_data.
        points = []
        for it in items:
            epi = it.get("epi_data")
            if epi:
                points.append({**epi, "published_at": it.get("published_at"), "link": it.get("link")})
        points.sort(key=lambda p: (p.get("epi_week") if p.get("epi_week") is not None else -1,
                                   p.get("published_at") or ""))
        # Keep only the most recent TRAJECTORY_WEEKS weeks for the curve.
        points = points[-TRAJECTORY_WEEKS:]

        # Representative (latest) item drives the headline fields.
        items_sorted = sorted(items, key=lambda a: a.get("published_at") or "")
        latest = items_sorted[-1]
        disease_name = latest.get("disease_other_label") or _DISEASE_PRETTY.get(latest.get("disease")) or latest.get("disease")
        # Guard: never surface an unnamed group as an "Unknown Outbreak" card
        # (extraction now drops unnamed alert-worthy items, this is belt-and-braces).
        if not disease_name or str(disease_name).strip().lower() in ("unknown", "other", "none"):
            log.info(f"Skipping outbreak group '{key}' -- no identifiable disease name")
            continue

        # A "sitrep" outbreak has a real multi-week epidemic curve (>=2 weekly
        # points, i.e. NCDC-style). Anything else (a single news article) is a
        # "signal" -- rendered as a concise, verify-then-act intelligence card
        # rather than an empty weekly-KPI shell.
        card_type = "sitrep" if len(points) >= 2 else "signal"
        latest_epi = points[-1] if points else None
        latest_week = int(latest_epi["epi_week"]) if latest_epi and latest_epi.get("epi_week") is not None else None
        top_states = (latest_epi.get("top_states") if latest_epi else None) or []

        # Trend direction from the last two weeks' new-confirmed counts.
        trend = "unknown"
        weekly = [p.get("confirmed_this_week") for p in points if p.get("confirmed_this_week") is not None]
        if len(weekly) >= 2:
            trend = "rising" if weekly[-1] > weekly[-2] else "falling" if weekly[-1] < weekly[-2] else "stable"

        # Plan cache key includes TODAY's date, the latest epi-week, and the
        # PLAN_VERSION -- so the brief regenerates (a) daily, since it is anchored
        # to "as of today" and the weather/forecast move (the user's top
        # priority), (b) when a new sitrep week arrives, and (c) when the prompt
        # itself changes. One LLM call per outbreak per day is the intended cost.
        today = _date.today().isoformat()
        if card_type == "sitrep":
            cache_key = f"{key}:wk{latest_week}:{today}:{PLAN_VERSION}"
            cached = plan_cache.get(cache_key)
            if cached:
                plan = cached
            else:
                log.info(f"Generating outbreak plan for '{disease_name}' (latest week {latest_week}, as of {today})")
                internal_text = internal_context_text(latest.get("disease"), top_states)
                plan = generate_outbreak_plan(
                    disease=disease_name,
                    trajectory_text=_trajectory_text(points),
                    top_states=", ".join(top_states),
                    weather_text=_weather_text(latest.get("weather")),
                    internal_text=internal_text,
                    today=today,
                )
                if plan:
                    plan_cache[cache_key] = plan
        else:  # signal card -> concise verify-then-act brief for a single news item
            cache_key = f"{key}:signal:{latest.get('id')}:{today}:{PLAN_VERSION}"
            cached = plan_cache.get(cache_key)
            if cached:
                plan = cached
            else:
                log.info(f"Generating signal brief for '{disease_name}' (as of {today})")
                internal_text = internal_context_text(latest.get("disease"), top_states)
                plan = generate_signal_brief(
                    disease=disease_name,
                    location=latest.get("location"),
                    summary=latest.get("summary"),
                    source=latest.get("source_label"),
                    published=latest.get("published_at"),
                    weather_text=_weather_text(latest.get("weather")),
                    internal_text=internal_text,
                    today=today,
                )
                if plan:
                    plan_cache[cache_key] = plan

        # Exposed as their own, separately-labeled fields (not just baked into
        # the AI plan's prose) so the UI can show exactly which numbers came
        # from scraped SOURCE DATA, which from OUR DATA, and which are FORECAST.
        our_burden = malaria_burden_for_states(top_states)
        our_forecast = malaria_forecast_for_states(top_states)

        outbreaks.append({
            "key": key,
            "card_type": card_type,             # "sitrep" (epi curve) | "signal" (news article)
            "disease": latest.get("disease"),
            "disease_name": disease_name,
            "severity": latest.get("severity"),
            "geography_level": latest.get("geography_level"),
            "location": latest.get("location"),
            "report_count": len(items),
            "latest_week": latest_week,
            "trend": trend,
            "top_states": top_states,
            "intervention": latest.get("intervention_recommendation"),

            # SOURCE DATA -- scraped/extracted from official sitreps (NACA/NMEP/NCDC/NTBLCP)
            "source": {
                "source_label": latest.get("source_label"),
                "latest_link": latest.get("link"),
                "latest_published_at": latest.get("published_at"),
                "latest_summary": latest.get("summary"),
                "trajectory": points,  # weekly epi_data, all extracted from sitrep PDFs
            },

            # OUR DATA -- FMOH's own internal warehouse, current/actual (not forecast)
            "our_data": our_burden,  # {state: {latest_month, latest_value, trend}}

            # FORECAST -- forward-looking projections (weather model + our SARIMAX)
            "forecast": {
                "weather": latest.get("weather"),  # includes rainfall_forecast_7day_mm (Open-Meteo forecast)
                "malaria": our_forecast,  # {state: {from_month, to_month, start_pred, end_pred, direction}} -- our SARIMAX
            },

            "cross_disease_correlation": latest.get("cross_disease_correlation"),
            "plan": plan,

            # Back-compat top-level aliases (existing frontend fields, unchanged behavior)
            "weather": latest.get("weather"),
            "latest_summary": latest.get("summary"),
            "trajectory": points,
            "source_label": latest.get("source_label"),
            "latest_link": latest.get("link"),
            "latest_published_at": latest.get("published_at"),
        })

    # Prune the daily-keyed cache so it doesn't grow without bound -- only
    # today's entries are ever served, so older days are safe to drop.
    today = _date.today().isoformat()
    plan_cache = {k: v for k, v in plan_cache.items() if f":{today}:" in k}
    news_store.save_plan_cache(plan_cache)
    # Most severe / most recent first.
    sev_rank = {"critical": 0, "warning": 1, "watch": 2, "informational": 3}
    outbreaks.sort(key=lambda o: (sev_rank.get(o["severity"], 9), -(o["latest_week"] or 0)))
    return outbreaks
