// Plain-language meaning for EVERY dataset column + the engineered/external features.
// Keys are matched case/punctuation-insensitively (handles truncated/encoded names).

export const ABBREV = [
  ['ACT', 'Artemisinin-based Combination Therapy — the first-line antimalarial drug'],
  ['RDT', 'Rapid Diagnostic Test — finger-prick malaria test'],
  ['LLIN', 'Long-Lasting Insecticidal Net — treated mosquito bed net'],
  ['ITN', 'Insecticide-Treated Net (mosquito net)'],
  ['IRS', 'Indoor Residual Spraying of insecticide'],
  ['IPTp', 'Intermittent Preventive Treatment in pregnancy'],
  ['IPT / IPT1', 'Intermittent Preventive Treatment (dose 1)'],
  ['SP / Fansidar', 'Sulfadoxine-Pyrimethamine — the drug used for IPTp'],
  ['ANC', 'Antenatal Care (pregnancy clinic visits)'],
  ['OPD / IPD', 'Out-Patient Dept / In-Patient Dept'],
  ['DTH', 'Deaths (reporting stream)'],
  ['TPR', 'Test Positivity Rate — % of tests that are positive'],
  ['U5', 'Children under 5 years (highest-risk group)'],
  ['MDC', 'Mass Distribution Campaign (how nets were sourced)'],
  ['MAL', 'Malaria (DHIS2 element prefix)'],
  ['[CONFIG]', 'A system/configured reporting-completeness metric'],
  ['PfPR', 'Plasmodium falciparum Parasite Rate — modelled prevalence'],
  ['NDVI', 'Normalized Difference Vegetation Index (greenness, satellite)'],
  ['ENSO / ONI', 'El Niño Southern Oscillation / Oceanic Niño Index'],
  ['IOD / DMI', 'Indian Ocean Dipole / Dipole Mode Index'],
  ['EIR', 'Entomological Inoculation Rate — infective bites per person'],
  ['R₀', 'Basic reproduction number (transmission potential)'],
  ['DTR', 'Diurnal Temperature Range (daily max − min)'],
]

export const GLOSSARY = {
  // ---- engineered base / target lags ----
  'lag1': 'Confirmed malaria cases 1 month ago (log scale)',
  'lag2': 'Confirmed malaria cases 2 months ago (log)',
  'lag3': 'Confirmed malaria cases 3 months ago (log)',
  'lag6': 'Confirmed cases 6 months ago (log) — semi-annual pattern',
  'lag12': 'Confirmed cases 12 months ago (log) — same month last year',
  'roll3': 'Average of the last 3 months of cases (log) — smoothed trend',
  'roll6': 'Average of the last 6 months of cases (log) — medium-term trend',
  'yoy_change': 'Year-over-year change in cases (log ratio) — growth/decline',
  'population': 'Population of the LGA (persons) — exposure / catchment size',
  'pop_density': 'Population per km² (population ÷ area)',
  'year': 'Calendar year (long-run trend)',
  'month': 'Calendar month 1–12 (seasonality)',
  'state_level': 'State identity — the state’s average historical case level',
  'lga_level': 'LGA identity — the LGA’s average historical case level',
  'spatial_lag1': 'Spillover — average cases in the rest of the state last month',
  // ---- derived climate / SEIR ----
  'rain_lag1': 'Rainfall 1 month ago (breeding-habitat lag — top global predictor)',
  'rain_lag2': 'Rainfall 2 months ago (sustained breeding)',
  'rain_cum3': 'Total rainfall over the last 3 months',
  'rain_anom': 'Rainfall anomaly — how far above/below the LGA’s normal for that month',
  'temp_lag1': 'Temperature 1 month ago (parasite-incubation lag)',
  'temp_suitability': 'Thermal suitability for transmission — peaks at 25 °C, ~0 below 16 °C / above 40 °C',
  'temp_anom': 'Temperature anomaly vs the LGA’s seasonal normal',
  'dtr': 'Diurnal temperature range (daily max − min) — wide range stresses mosquitoes',
  'hum_lag1': 'Humidity 1 month ago (mosquito-survival lag)',
  'eir_proxy': 'Entomological Inoculation Rate proxy = suitability × rainfall × humidity (transmission pressure)',
  'recruitment_proxy': 'Mosquito recruitment φ(T,R) = rainfall_lag2 × thermal suitability',
  'mortality_proxy': 'Mosquito mortality proxy — rises as temperature moves away from 25 °C',
  'r0_proxy': 'Reproduction-number proxy = test-positivity × case-growth',
  'tpr_lag1': 'Test positivity rate 1 month ago — leading indicator of incidence',
  // ---- real external data ----
  'ndvi': 'Vegetation greenness (NDVI, satellite) — vector habitat: shade, humidity, resting sites',
  'ndvi_anom': 'NDVI anomaly — greener/browner than the LGA’s seasonal normal',
  'ndvi_lag1': 'NDVI 1 month ago (vegetation → habitat lag)',
  'enso_oni': 'El Niño index (NOAA ONI) — El Niño shifts rainfall (inter-annual)',
  'iod_dmi': 'Indian Ocean Dipole index — drives African rainfall anomalies',
  'elevation': 'Ground elevation at the LGA centre (m) — above ~2000 m has no malaria',
  'area_sqkm': 'Land area of the LGA (km²)',
  'latitude': 'How far north the LGA is — Nigeria’s north–south transmission gradient',
  'pfpr': 'Malaria prevalence (PfPR 2-10, Malaria Atlas Project) — % of 2–10-yr-olds infected',
  'poverty_mpi_h': 'Multidimensional poverty rate (% of people poor across health/education/living-standards)',
  'dep_schooling': 'Education deprivation — % of people lacking schooling',
  'dep_electricity': 'Electricity deprivation — % of households without electricity',
  'dep_water': 'Water deprivation — % without safe drinking water',
  'dep_housing': 'Housing deprivation — % in inadequate housing',
  // ---- DHIS2 programme indicators ----
  'Access to an ITN': 'People with access to an insecticide-treated net',
  'ACT Given - Total': 'Total ACT antimalarial treatment courses dispensed',
  'Anti-Malarial treatment': 'Patients given antimalarial treatment',
  'Anti-Malarial treatment among children under 5 yrs': 'Under-5 children given antimalarial treatment',
  'Children <5 yrs who received LLIN': 'Under-5 children given a treated bed net',
  'Children age 6-59 months tested positive for Malaria': 'Children 6–59 months who tested positive for malaria',
  'Children under age 5 had a fever in the 2 weeks before the survey': 'Under-5s with fever in the past 2 weeks (survey)',
  'Children under age 5 with a fever received ACT': 'Feverish under-5s who got ACT treatment',
  'Children with a fever had blood taken for testing': 'Feverish children who had a blood/malaria test',
  'Closing Balance - Rapid Diagnostic Test (RDT)': 'RDT test kits remaining in stock at month end',
  'IPTp1 Coverage (institutional)': 'Pregnant women given the 1st dose of preventive malaria therapy',
  'IPTp2 Coverage (institutional)': 'Pregnant women given the 2nd dose of preventive therapy',
  'IPTp3 Coverage (institutional)': 'Pregnant women given the 3rd dose',
  'IPTp>=4 Coverage (institutional)': 'Pregnant women given 4+ doses of preventive therapy',
  'LLIN given – Total': 'Total treated bed nets distributed',
  'MAL - Malaria cases confirmed (number)': 'THE TARGET — lab-confirmed malaria cases',
  'MAL - Malaria cases tested with microscopy': 'Cases tested by microscope',
  'MAL - Malaria cases tested with RDT': 'Cases tested by rapid diagnostic test',
  'MAL - Malaria deaths inpatient(Under 5)': 'Under-5 malaria deaths among admitted patients',
  'MAL - Malaria inpatient admissions': 'Patients admitted to hospital for malaria',
  'MAL - Non-malaria deaths inpatient': 'Inpatient deaths from causes other than malaria',
  'MAL - Non-malaria outpatient cases': 'Outpatient visits not due to malaria',
  'MAL - Total reported malaria cases (confirmed + presumed)': 'All reported malaria cases — confirmed plus clinically-presumed',
  'Number of malaria cases treated with artemisinin-based combination': 'Cases treated with ACT',
  'Number of malaria positive cases by microscopy': 'Microscopy-positive malaria cases',
  'Number of malaria positive cases by rapid diagnostic test (RDT)': 'RDT-positive malaria cases',
  'Number of suspected malaria cases': 'Suspected (not-yet-confirmed) malaria cases',
  'Persons with Severe Malaria given recommended pre-referral treatment': 'Severe cases given emergency treatment before referral',
  'Persons with Severe Malaria treated with Artesunate injection': 'Severe cases treated with injectable artesunate',
  'Persons with Severe Malaria treated with other pre referral treatment': 'Severe cases given other pre-referral treatment',
  'Severe Malaria cases seen': 'Severe (complicated) malaria cases seen',
  'Severe Malaria Treatment': 'Severe malaria cases treated',
  'Treatment with Artemisinin-based Combination Therapy (ACT) among': 'Patients treated with ACT (subgroup)',
  'Children under 5 sleeping under insecticide-treated nets (ITNs)': 'Under-5s who slept under a treated net',
  'Children under 5 yr who slept under an ITN': 'Under-5s who slept under a treated net (survey)',
  '[CONFIG] MAL - Reporting completeness - DTH (%)': 'Data quality — % of facilities reporting the deaths stream',
  '[CONFIG] MAL - Reporting completeness - IPD (%)': 'Data quality — % of facilities reporting inpatient data',
  '% Confirmed Malaria (RDT or Microscopy)': '% of suspected cases confirmed positive by any test',
  '% Confirmed uncomplicated Malaria': '% of cases that are confirmed and uncomplicated',
  'Estimated malaria cases in 2021': 'Modelled/estimated malaria cases (2021 baseline)',
  'Estimated malaria cases in 2022': 'Modelled/estimated malaria cases (2022 baseline)',
  'Estimated malaria cases in 2023': 'Modelled/estimated malaria cases (2023 baseline)',
  'Fever Testing Rate': '% of fever cases that were tested for malaria',
  'Households using an improved sanitation facility': '% of households with improved sanitation',
  'Households using Improved Water as Source of drinking water': '% of households using improved drinking water',
  'Households with at least one ITN': '% of households owning at least one treated net',
  'Literacy among women': '% of women who are literate',
  'Malaria diagnostic usage (Percentage of children under age 5 with)': '% of feverish under-5s who got a malaria test',
  'Malaria prevalence according to RDT among children': '% of children testing positive by RDT (prevalence)',
  'MAL - Case fatality rate (malaria admissions)': '% of admitted malaria patients who died',
  'MAL - % of all-admissions/all outpatients': 'Malaria admissions as a share of all outpatients',
  'MAL - % of all-deaths/all admissions': 'Malaria deaths as a share of all admissions',
  'MAL - % of malaria tested cases by RDT': '% of malaria tests done with RDT (vs microscopy)',
  'MAL - % of suspected malaria cases tested': '% of suspected cases that were actually tested',
  'MAL - Percentage of malaria deaths': 'Malaria deaths as % of all deaths',
  'MAL - Percentage of malaria IPD': 'Malaria as % of inpatient cases',
  'MAL - Percentage of malaria OPD cases': 'Malaria as % of outpatient cases',
  'MAL - Slide positivity rate (microscopy)': '% of microscopy slides positive for malaria',
  'MAL - Test positivity rate (RDT)': '% of RDTs positive — key transmission-intensity signal',
  '% of all Antenatal care clients receiving malaria IPT': '% of pregnancy-clinic clients given preventive therapy',
  '% of Antenatal 1st Visits receiving IPT1': '% of first ANC visits given the 1st preventive dose',
  '% of Antenatal 1st Visits receiving LLIN': '% of first ANC visits given a treated net',
  '% of Antimalaria with mobile authentication service': '% of antimalarials verified via mobile anti-counterfeit check',
  '% of clinically diagnosed malaria given ACT': '% of clinically-diagnosed cases treated with ACT',
  '% of confirmed uncomplicated malaria given ACT': '% of confirmed uncomplicated cases treated with ACT',
  '% of confirmed uncomplicated malaria given other antimalaria': '% given a non-ACT antimalarial',
  '% of Fever cases tested positive with Microscopy': '% of fever cases positive by microscopy',
  '% of Fever cases tested positive with RDT': '% of fever cases positive by RDT',
  '% of Fever cases Tested with Microscopy': '% of fever cases tested by microscopy',
  '% of Fever cases Tested with RDT': '% of fever cases tested by RDT',
  '% of Malaria cases clinically diagnosed': '% of cases diagnosed on symptoms alone (no test)',
  '% of Persons Clinically diagnosed with Malaria treated with ACT': '% of clinically-diagnosed people treated with ACT',
  '% of suspected malaria receiving parasitological test': '% of suspected cases given a lab/parasite test',
  '% of Under 5 deaths attributable to Malaria': '% of under-5 deaths caused by malaria',
  'Ownership of at least one mosquito net': '% of households owning any mosquito net',
  'Ownership of insecticide-treated nets': '% of households owning a treated net',
  'Percentage of children age 6-59 months classified as having anaemia': '% of young children with anaemia (often malaria-related)',
  'Percentage of children who received ACT': '% of children treated with ACT',
  'Percentage of households owning at least one ITN': '% of households with ≥1 treated net',
  'Percentage of households with at least one mosquito net': '% of households with ≥1 net of any kind',
  'Percentage of malaria cases confirmed with laboratory diagnostic': '% of cases confirmed by a lab test',
  'Percentage of women age 15-49 who say there are ways to avoid': '% of women aware malaria can be prevented',
  'Percentage of women who took any IPT (SP/Fansidar)': '% of women who took any preventive malaria therapy in pregnancy',
  '% Percentage who have seen or heard a malaria message in the past': '% who recently saw/heard a malaria-awareness message',
  'Percentage who received 2 or more doses': '% who received ≥2 preventive doses',
  'Percentage who received 3 or more doses of SP': '% who received ≥3 doses of the IPTp drug (SP)',
  'Percentage who received one or more doses of SP/Fansidar': '% who received ≥1 dose of SP/Fansidar',
  'Percentage who received only 1 dose of SP': '% who received exactly 1 dose of SP',
  'Percentage who received three or more doses of SP/Fansidar': '% who received ≥3 doses of SP/Fansidar',
  'Percentage who received two or more doses of SP/Fansidar': '% who received ≥2 doses of SP/Fansidar',
  'Percentage who state there are ways to avoid getting malaria': '% who believe malaria is preventable',
  'Percentage with a fever & tested for malaria': '% of feverish people who were tested',
  'Persons with access to an insecticide treated mosquito net (ITN)': 'People with access to a treated net',
  'Pregnant women attending antenatal care at least once and received': 'Pregnant women with ≥1 ANC visit who got preventive therapy',
  'Pregnant women sleeping under insecticide-treated nets (ITNs)': 'Pregnant women who slept under a treated net',
  'Pregnant women who slept under an ITN': 'Pregnant women who slept under a treated net (survey)',
  'Reporting completeness - OPD (%)': 'Data quality — % of facilities reporting outpatient data',
  'Sources of ITNs-MDC': 'Share of nets obtained from a Mass Distribution Campaign',
  'Test Positivity Rate(TPR) (Microscopy)': '% of microscopy tests positive',
  'Test Positivity Rate(TPR) (RDT)': '% of RDTs positive',
  '% U5 fever to OPD attendance': 'Under-5 fever visits as % of all outpatient attendance',
  'Under 5 mortality rate(Facility)': 'Under-5 deaths per facility caseload',
  '% Under 5 receiving LLIN': '% of under-5 children given a treated net',
  'Use of clean fuels and technologies for cooking': '% of households cooking with clean fuel',
  'Use of ITNs': '% of people using a treated net',
  'Use of ITNs by children under age 5': '% of under-5s using a treated net',
  'Use of ITNs by pregnant women': '% of pregnant women using a treated net',
  'Vector Control — LLINs': 'Vector-control activity — treated nets',
  'temperature_mean_c': 'Mean monthly temperature (°C)',
  'temperature_max_c': 'Mean daily maximum temperature (°C)',
  'temperature_min_c': 'Mean daily minimum temperature (°C)',
  'humidity_pct': 'Relative humidity (%) — affects mosquito survival',
  'rainfall_mm_day': 'Rainfall (mm/day) — drives mosquito breeding',
  'wind_speed_ms': 'Wind speed (m/s)',
  'solar_kwh_m2_day': 'Solar radiation (kWh/m²/day)',
}

const _norm = (s) => String(s).toLowerCase().replace(/[^a-z0-9]/g, '')
const _index = Object.entries(GLOSSARY).map(([k, v]) => [_norm(k), v])
export function meaningFor(name) {
  if (GLOSSARY[name]) return GLOSSARY[name]
  const n = _norm(name)
  for (const [k, v] of _index) {
    if (k === n) return v
    if (k.length >= 14 && (n.startsWith(k.slice(0, 18)) || k.startsWith(n.slice(0, 18)))) return v
  }
  return '—'
}

// ---- authentic source links (real, fetched) ----
export const SOURCES = {
  dhis2: { label: 'Your DHIS2 facility extract (final_malaria_data.csv), aggregated to LGA-month', url: null },
  weather: { label: 'Climate reanalysis already in your dataset (final_malaria_data.csv)', url: null },
  target: { label: 'Computed from the confirmed-cases target (DHIS2)', url: null },
  oni: { label: 'NOAA CPC — Oceanic Niño Index (ONI)', url: 'https://www.cpc.ncep.noaa.gov/data/indices/oni.ascii.txt' },
  dmi: { label: 'NOAA PSL — Dipole Mode Index (HadISST)', url: 'https://psl.noaa.gov/gcos_wgsp/Timeseries/Data/dmi.had.long.data' },
  ndvi: { label: 'Provided file nga-ndvi-subnat-full.csv (FEWS NET / VAM subnational NDVI)', url: 'https://earlywarning.usgs.gov/fews' },
  srtm: { label: 'OpenTopoData — SRTM 30 m elevation (queried at each LGA centroid)', url: 'https://www.opentopodata.org' },
  ocha: { label: 'OCHA Nigeria admin-2 boundaries (HDX)', url: 'https://data.humdata.org/dataset/cod-ab-nga' },
  map: { label: 'Malaria Atlas Project — PfPR 2-10, 2024 raster (WMS point query at LGA centroid)', url: 'https://data.malariaatlas.org/maps' },
  mpi: { label: 'OPHI / NBS Global MPI 2019 — Nigeria subnational, state level (HDX)', url: 'https://data.humdata.org/dataset/97292577-fe75-4dc2-a70f-6b83c871ef7c' },
}

// ---- per-column derivation + interpretation + source (authentic, not fabricated) ----
const D = (derivation, interpret, src) => ({ derivation, interpret, src })
export const DETAIL = {
  // engineered from the target (DHIS2 confirmed cases)
  lag1: D('log1p(confirmed cases) shifted back 1 month, per LGA.', 'Higher = more cases recently; the single strongest predictor.', 'target'),
  lag2: D('log1p(cases) shifted back 2 months.', 'Recent transmission momentum.', 'target'),
  lag3: D('log1p(cases) shifted back 3 months.', 'Quarter-ago level.', 'target'),
  lag6: D('log1p(cases) shifted back 6 months.', 'Half-year (opposite-season) signal.', 'target'),
  lag12: D('log1p(cases) shifted back 12 months.', 'Same month last year — anchors the seasonal cycle.', 'target'),
  roll3: D('Mean of lag1…lag3 (log cases).', 'Smoothed recent level (less noise).', 'target'),
  roll6: D('Mean of the previous 6 months (log cases).', 'Medium-term trend.', 'target'),
  yoy_change: D('lag1 − (cases 13 months ago), in log space ≈ log growth ratio.', '>0 = rising vs a year ago; <0 = falling.', 'target'),
  spatial_lag1: D('Average log-cases of the whole state, shifted back 1 month.', 'High = neighbours had high burden last month (spillover).', 'target'),
  state_level: D('Mean log-cases of the state over the TRAINING window only (leakage-free identity encoding).', 'A stand-in for "which state" without overfitting.', 'target'),
  lga_level: D('Mean log-cases of the LGA over the training window only.', 'A stand-in for "which LGA".', 'target'),
  population: D('NPC state projection split to LGAs by facility share; grown 2.5%/yr.', 'Bigger population → more cases at the same rate.', 'dhis2'),
  pop_density: D('population ÷ area_sqkm.', 'People per km²; denser areas can sustain different transmission.', 'srtm'),
  year: D('Calendar year.', 'Captures the long-run upward trend.', 'target'),
  month: D('Calendar month 1–12.', 'Lets trees learn the seasonal shape directly.', 'target'),
  // climate derived (from the dataset's monthly weather)
  rain_lag1: D('rainfall_mm_day shifted back 1 month, per LGA.', 'Rain now → mosquitoes/cases ~1–2 months later.', 'weather'),
  rain_lag2: D('rainfall_mm_day shifted back 2 months.', 'Sustained-breeding lag.', 'weather'),
  rain_cum3: D('Sum of rainfall over the last 3 months.', 'Total water available for breeding habitat.', 'weather'),
  rain_anom: D('(rainfall − the LGA’s mean for that calendar month) ÷ that month’s std. A z-score.', '+1 ≈ one std wetter than normal for that month; −1 = drier.', 'weather'),
  temp_lag1: D('temperature_mean_c shifted back 1 month.', 'Parasite-incubation lag.', 'weather'),
  temp_suitability: D('Thermal-response curve peaking at 25 °C (Plasmodium optimum, Mordecai 2013): exp(−((mean_temp − 25)/7)²).', '1.0 = ideal ~25 °C; falls toward 0 in cold/hot months.', 'weather'),
  temp_anom: D('Temperature z-score vs the LGA’s normal for that month.', '+ = warmer than usual that month.', 'weather'),
  dtr: D('temperature_max_c − temperature_min_c. NOTE: both are the dataset’s MONTHLY values (monthly mean of the daily max / daily min), so this is the typical day–night swing during the month — not one specific day.', 'Bigger swing (hot days, cold nights) stresses mosquitoes & slows the parasite; smaller swing is more favourable.', 'weather'),
  hum_lag1: D('humidity_pct shifted back 1 month.', 'Drier last month → shorter mosquito lifespan.', 'weather'),
  // SEIR mechanistic proxies (Ross–Macdonald mappings)
  eir_proxy: D('temp_suitability × (rain/(rain+5)) × (humidity/100). A unitless climate-transmission index.', 'Higher = more favourable conditions for infective biting.', 'weather'),
  recruitment_proxy: D('(rain_lag2/(rain_lag2+5)) × temp_suitability — the SEIR φ(T,R) mosquito-emergence term.', 'Higher = more new mosquitoes expected.', 'weather'),
  mortality_proxy: D('clip(|mean_temp − 25| / 15, 0, 1) — the SEIR μᵥ(T) term.', 'Higher (temps far from 25 °C) = mosquitoes die faster.', 'weather'),
  r0_proxy: D('(test-positivity 1mo ago ÷ 100) × (1 + year-over-year case growth) — a crude R₀ signal.', 'Higher = transmission accelerating.', 'target'),
  tpr_lag1: D('MAL - Test positivity rate (RDT) shifted back 1 month.', 'Rising positivity precedes rising cases.', 'dhis2'),
  // real external data
  ndvi: D('Monthly mean of the FEWS NET dekadal vegetation index (vim) for the LGA, matched by OCHA PCODE.', '~0.2 = bare/dry; ~0.8 = dense green vegetation (more vector habitat).', 'ndvi'),
  ndvi_anom: D('viq − 100, i.e. % above/below the pixel’s long-term seasonal mean.', '+10 = 10% greener than normal for that month; −10 = browner.', 'ndvi'),
  ndvi_lag1: D('NDVI shifted back 1 month (literature lag of vegetation→habitat is 2–3 months).', 'Last month’s greenness.', 'ndvi'),
  enso_oni: D('NOAA ONI = 3-month running mean of sea-surface-temperature anomalies in the Niño-3.4 region (5°N–5°S, 120°–170°W) vs a 30-yr base. We attach each season’s value to its CENTRE month; it is a global signal so it is identical across all LGAs in a month.', '≥ +0.5 °C (sustained) = El Niño; ≤ −0.5 = La Niña; between = neutral. 2023–24 hit ~+2 (strong El Niño).', 'oni'),
  iod_dmi: D('NOAA Dipole Mode Index = the SST difference between the western (50–70°E) and eastern (90–110°E) tropical Indian Ocean (HadISST). National monthly value.', '+ (positive IOD) = wetter East Africa / drier east Indian Ocean; − = the reverse. West-African effect is weaker than ENSO.', 'dmi'),
  elevation: D('SRTM 30 m elevation sampled at the LGA centroid (centre point) via OpenTopoData.', 'Metres above sea level; above ~1,600–2,000 m it gets too cold for stable transmission.', 'srtm'),
  area_sqkm: D('LGA land area from the OCHA admin-2 boundaries.', 'Square kilometres (used for population density).', 'ocha'),
  latitude: D('Centroid latitude from the OCHA admin-2 boundaries.', 'Higher = further north (drier Sahel, more seasonal malaria).', 'ocha'),
  pfpr: D('Malaria Atlas Project modelled Pf parasite rate (2–10 yr-olds), 2024 raster, read at the LGA centroid. One value per LGA (applied to all months).', '% of 2–10-year-olds infected: Nigeria ~9–47% by LGA (mean ~28%); low in big cities, high in the rural north/SE.', 'map'),
  poverty_mpi_h: D('OPHI/NBS Multidimensional Poverty Index headcount (H) for the LGA’s STATE (2019), applied to all its LGAs.', '% of people who are multidimensionally poor: ~2% (Lagos) to ~86% (far north).', 'mpi'),
  dep_schooling: D('MPI censored headcount for the "years of schooling" indicator, by state.', '% of people who are poor AND in a household lacking schooling. Higher = less education.', 'mpi'),
  dep_electricity: D('MPI censored headcount for the "electricity" indicator, by state.', '% poor AND without electricity. Higher = worse access.', 'mpi'),
  dep_water: D('MPI censored headcount for the "drinking water" indicator, by state.', '% poor AND without safe water.', 'mpi'),
  dep_housing: D('MPI censored headcount for the "housing" indicator, by state.', '% poor AND in inadequate housing.', 'mpi'),
  // raw weather
  temperature_mean_c: D('Monthly mean temperature (°C), from the dataset’s weather columns.', 'Transmission optimum ~25 °C.', 'weather'),
  temperature_max_c: D('Monthly value of daily-maximum temperature (°C).', 'Hot extremes (>40 °C) kill mosquitoes.', 'weather'),
  temperature_min_c: D('Monthly value of daily-minimum (night) temperature (°C).', 'Cold nights kill mosquitoes / stall the parasite.', 'weather'),
  humidity_pct: D('Monthly relative humidity (%).', 'Higher = mosquitoes live longer → longer transmission season.', 'weather'),
  rainfall_mm_day: D('Monthly mean daily rainfall (mm/day).', 'Drives breeding; very heavy rain can flush larvae (non-linear).', 'weather'),
  wind_speed_ms: D('Monthly mean wind speed (m/s).', 'Affects mosquito dispersal/biting.', 'weather'),
  solar_kwh_m2_day: D('Monthly solar radiation (kWh/m²/day).', 'Proxy for cloud cover / micro-climate.', 'weather'),
}
const _detIndex = Object.entries(DETAIL).map(([k, v]) => [_norm(k), v])
const DHIS2_FALLBACK = D('Aggregated from facility records to LGA-month — SUM for absolute counts, MEAN for rates/percentages.', '', 'dhis2')
export function detailFor(name) {
  if (DETAIL[name]) return DETAIL[name]
  const n = _norm(name)
  for (const [k, v] of _detIndex) { if (k === n) return v }
  return DHIS2_FALLBACK   // every remaining column is a DHIS2/aggregated indicator
}
